--- 
:type: widget
:name: app:message
:version: "1.0.1"
:dependencies: 
- :type: websdk
  :version: ">=2.1"
  :name: websdk
:tags: [ logic ]
:description: "app:message is a non-visual widget for sending a message either locally or remotely"
