--- 
:type: widget
:name: app:validation
:version: 1.0
:dependencies: 
- :type: websdk
  :version: ">=2.1"
  :name: websdk
:tags: [ logic ]
:description: "app:validation is a logic component for controlling multi-state validation across different elements"