--- 
:type: widget
:name: app:iterator
:version: 1.0.3
:dependencies: 
- :type: websdk
  :version: ">=2.1.2"
  :name: websdk
:tags: [ layout ]
:description: "app:iterator is a UI control for iterating over a set of array values from a message"
