--- 
:type: widget
:name: app:search
:version: 1.0.1
:dependencies: 
- :type: websdk
  :version: ">=2.1.2"
  :name: websdk
:tags: [ uicontrol, search ]
:description: "app:search is a UI control for performing dynamic searches based on key entry (without having to click a button)"
